import os

# Include necessary environment
env = SConscript('godot-cpp/SConstruct')

# Append the source directory to the include path
env.Append(CPPPATH=["src/"])

#for libraries
#env.Append(LIB="...")
#env.Append(LIBPATH="...")

#src = Glob("src/**/*.cpp")

# Function to collect CPP files recursively from a directory
def collect_cpp_files(root):
    cpp_files = []
    for dirpath, _, filenames in os.walk(root):
        for filename in filenames:
            if filename.endswith('.cpp'):
                cpp_files.append(os.path.join(dirpath, filename))
    return cpp_files

# Collect all CPP files in the src directory
src = collect_cpp_files("src")

if env['platform'] == 'linux':
	libpath = '../libtest{}{}'.format(env['suffix'], env['SHLIBSUFFIX'])
	sharedlib = env.SharedLibrary(libpath, src)
	Default(sharedlib)

if env['platform'] == 'windows': # TODO
	pass
if env['platform'] == 'android': # TODO
	pass

