import os

env = SConscript('godot-cpp/SConstruct')


env.Append(CPPPATH="src/")

#for libraries
#env.Append(LIB="...")
#env.Append(LIBPATH="...")

#src = Glob("src/**/*.cpp")


src = collect_cpp_files("src")

if env['platform'] == 'linux':
	libpath = '../libtest{}{}'.format(env['suffix'], env['SHLIBSUFFIX'])
	sharedlib = env.SharedLibrary(libpath, src)
	Default(sharedlib)
if env['platform'] == 'windows': # TODO
	pass
if env['platform'] == 'android': # TODO
	pass
	
